"""stat

Revision ID: 52d6e1f4539f
Revises: 
Create Date: 2021-04-13 23:53:33.908722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d6e1f4539f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abcobjs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abcobjs_name'), 'abcobjs', ['name'], unique=False)
    op.create_index(op.f('ix_abcobjs_path'), 'abcobjs', ['path'], unique=False)
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('stat_path', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['model_name'], ['abcobjs.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_body'), 'stat', ['body'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stat_body'), table_name='stat')
    op.drop_table('stat')
    op.drop_index(op.f('ix_abcobjs_path'), table_name='abcobjs')
    op.drop_index(op.f('ix_abcobjs_name'), table_name='abcobjs')
    op.drop_table('abcobjs')
    # ### end Alembic commands ###
